version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    entrypoint: /code/entrypoint.backend.dev.sh
